security:
    # Authentification JWT (LexikJWTBundle) — hachage Argon2id (CDC §6.1).

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: argon2id

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    # Hiérarchie des rôles métier (CDC §3)
    # Chef de pôle hérite des droits du cadre, qui hérite du soignant.
    role_hierarchy:
        ROLE_CADRE:     [ROLE_SOIGNANT]
        ROLE_CHEF_POLE: [ROLE_CADRE]

    firewalls:
        dev_tools:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # Émission du JWT + refresh token à partir d'un couple email/mot de passe.
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            login_throttling:
                max_attempts: 5
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Routes protégées par JWT (header Authorization: Bearer) + rafraîchissement de token.
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            jwt: ~
            refresh-jwt:
                check_path: /api/token/refresh
            logout:
                path: /api/logout

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
