<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Bascule de l'authentification Azure AD vers JWT + Argon2id (CDC §6.1).
 * Migration des identifiants User/Declaration vers UUID v4 (CDC §6.2).
 */
final class Version20260712041736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Migration User/Declaration vers UUID v4, ajout password (Argon2id), suppression des champs Azure AD, ajout refresh_tokens.';
    }

    public function up(Schema $schema): void
    {
        // --- Phase 1 : suppression de toutes les FK impliquant les colonnes id qui vont changer de type ---
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT fk_7aa3dac2f6203804');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT fk_7aa3dac22b4cda96');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT fk_7aa3dac246d22c7c');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT fk_7aa3dac2ec439bc');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT fk_7aa3dac2ed5ca9e6');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT fk_e19d9ad2419c3385');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT fk_e19d9ad2b03a8386');
        $this->addSql('ALTER TABLE suggestion_rmm DROP CONSTRAINT fk_f5745fecc06258a3');
        $this->addSql('ALTER TABLE user_service DROP CONSTRAINT fk_b99084d8a76ed395');
        $this->addSql('ALTER TABLE user_service DROP CONSTRAINT fk_b99084d8ed5ca9e6');
        $this->addSql('DROP INDEX idx_7aa3dac2f6203804');
        $this->addSql('DROP INDEX idx_7aa3dac22b4cda96');
        $this->addSql('DROP INDEX idx_7aa3dac246d22c7c');
        $this->addSql('DROP TABLE gravite');
        $this->addSql('DROP TABLE statut');
        $this->addSql('DROP TABLE type_ei');

        // --- Phase 2 : refresh_tokens (LexikJWT / GesdinetJWTRefreshToken) ---
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');

        // --- Phase 3 : Declaration — nouveaux champs + statut/gravite/typeEI en enum string + UUID ---
        $this->addSql('ALTER TABLE declaration ADD lieu_different_detail TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD type_ei VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE declaration ADD gravite VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD is_eigs BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE declaration ADD statut VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE declaration ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD consequences_autres BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD consequences_autres_detail TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD mesures_immediates_patient BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD mesures_immediates_patient_detail TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD mesures_immediates_proches BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD autres_mesures TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD suggestion_rmm BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE declaration ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE declaration ADD submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE declaration ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE declaration DROP statut_id');
        $this->addSql('ALTER TABLE declaration DROP gravite_id');
        $this->addSql('ALTER TABLE declaration DROP type_ei_id');
        $this->addSql('ALTER TABLE declaration ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE declaration ALTER id TYPE UUID USING id::text::uuid');
        $this->addSql('ALTER TABLE declaration ALTER declarant_id TYPE UUID USING declarant_id::text::uuid');
        $this->addSql('ALTER TABLE declaration ALTER service_id TYPE UUID USING service_id::text::uuid');

        // --- Phase 4 : Pole ---
        $this->addSql('ALTER TABLE pole ADD created_by_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE pole DROP created_by');
        $this->addSql('ALTER TABLE pole ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE pole ALTER id TYPE UUID USING id::text::uuid');

        // --- Phase 5 : Service ---
        $this->addSql('ALTER TABLE service DROP created_by');
        $this->addSql('ALTER TABLE service ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE service ALTER id TYPE UUID USING id::text::uuid');
        $this->addSql('ALTER TABLE service ALTER pole_id TYPE UUID USING pole_id::text::uuid');
        $this->addSql('ALTER TABLE service ALTER created_by_id TYPE UUID USING created_by_id::text::uuid');
        $this->addSql('ALTER TABLE service ALTER created_by_id DROP NOT NULL');

        // --- Phase 6 : SuggestionRmm ---
        $this->addSql('ALTER TABLE suggestion_rmm DROP updated_at');
        $this->addSql('ALTER TABLE suggestion_rmm ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE suggestion_rmm ALTER id TYPE UUID USING id::text::uuid');
        $this->addSql('ALTER TABLE suggestion_rmm ALTER declaration_id TYPE UUID USING declaration_id::text::uuid');
        $this->addSql('ALTER TABLE suggestion_rmm ALTER declaration_id SET NOT NULL');

        // --- Phase 7 : User — abandon Azure AD, ajout password Argon2id + UUID ---
        $this->addSql('ALTER TABLE "user" ADD password VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD roles JSON NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD created_by_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP oid');
        $this->addSql('ALTER TABLE "user" DROP display_name');
        $this->addSql('ALTER TABLE "user" DROP tenant_id');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE UUID USING id::text::uuid');
        $this->addSql('ALTER TABLE "user" ALTER last_login_at DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649B03A8386 ON "user" (created_by_id)');

        // --- Phase 8 : user_service (table de jonction) ---
        $this->addSql('ALTER TABLE user_service ALTER user_id TYPE UUID USING user_id::text::uuid');
        $this->addSql('ALTER TABLE user_service ALTER service_id TYPE UUID USING service_id::text::uuid');

        // --- Phase 9 : ré-ajout de toutes les FK, maintenant que tous les id sont UUID ---
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC2EC439BC FOREIGN KEY (declarant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC2ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pole ADD CONSTRAINT FK_FD6042E1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FD6042E1B03A8386 ON pole (created_by_id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2419C3385 FOREIGN KEY (pole_id) REFERENCES pole (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suggestion_rmm ADD CONSTRAINT FK_F5745FECC06258A3 FOREIGN KEY (declaration_id) REFERENCES declaration (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service ADD CONSTRAINT FK_B99084D8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service ADD CONSTRAINT FK_B99084D8ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        throw new \Doctrine\Migrations\Exception\IrreversibleMigration('Migration destructive (abandon des champs Azure AD, UUID) — restaurer depuis une sauvegarde si nécessaire.');
    }
}
