<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706043019 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE declaration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_constat TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_survenue TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu_different BOOLEAN NOT NULL, declarant_id INT NOT NULL, service_id INT NOT NULL, statut_id INT NOT NULL, gravite_id INT NOT NULL, type_ei_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AA3DAC2EC439BC ON declaration (declarant_id)');
        $this->addSql('CREATE INDEX IDX_7AA3DAC2ED5CA9E6 ON declaration (service_id)');
        $this->addSql('CREATE INDEX IDX_7AA3DAC2F6203804 ON declaration (statut_id)');
        $this->addSql('CREATE INDEX IDX_7AA3DAC22B4CDA96 ON declaration (gravite_id)');
        $this->addSql('CREATE INDEX IDX_7AA3DAC246D22C7C ON declaration (type_ei_id)');
        $this->addSql('CREATE TABLE gravite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(20) NOT NULL, libelle VARCHAR(100) NOT NULL, is_eigs BOOLEAN NOT NULL, ordre INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pole (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, pole_id INT DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD2419C3385 ON service (pole_id)');
        $this->addSql('CREATE INDEX IDX_E19D9AD2B03A8386 ON service (created_by_id)');
        $this->addSql('CREATE TABLE statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(100) NOT NULL, ordre INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE suggestion_rmm (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre_jour TEXT NOT NULL, is_auto BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, declaration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F5745FECC06258A3 ON suggestion_rmm (declaration_id)');
        $this->addSql('CREATE TABLE type_ei (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, oid VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, tenant_id VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_service (user_id INT NOT NULL, service_id INT NOT NULL, PRIMARY KEY (user_id, service_id))');
        $this->addSql('CREATE INDEX IDX_B99084D8A76ED395 ON user_service (user_id)');
        $this->addSql('CREATE INDEX IDX_B99084D8ED5CA9E6 ON user_service (service_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC2EC439BC FOREIGN KEY (declarant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC2ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC2F6203804 FOREIGN KEY (statut_id) REFERENCES statut (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC22B4CDA96 FOREIGN KEY (gravite_id) REFERENCES gravite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE declaration ADD CONSTRAINT FK_7AA3DAC246D22C7C FOREIGN KEY (type_ei_id) REFERENCES type_ei (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2419C3385 FOREIGN KEY (pole_id) REFERENCES pole (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suggestion_rmm ADD CONSTRAINT FK_F5745FECC06258A3 FOREIGN KEY (declaration_id) REFERENCES declaration (id)');
        $this->addSql('ALTER TABLE user_service ADD CONSTRAINT FK_B99084D8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_service ADD CONSTRAINT FK_B99084D8ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT FK_7AA3DAC2EC439BC');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT FK_7AA3DAC2ED5CA9E6');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT FK_7AA3DAC2F6203804');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT FK_7AA3DAC22B4CDA96');
        $this->addSql('ALTER TABLE declaration DROP CONSTRAINT FK_7AA3DAC246D22C7C');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2419C3385');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2B03A8386');
        $this->addSql('ALTER TABLE suggestion_rmm DROP CONSTRAINT FK_F5745FECC06258A3');
        $this->addSql('ALTER TABLE user_service DROP CONSTRAINT FK_B99084D8A76ED395');
        $this->addSql('ALTER TABLE user_service DROP CONSTRAINT FK_B99084D8ED5CA9E6');
        $this->addSql('DROP TABLE declaration');
        $this->addSql('DROP TABLE gravite');
        $this->addSql('DROP TABLE pole');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE statut');
        $this->addSql('DROP TABLE suggestion_rmm');
        $this->addSql('DROP TABLE type_ei');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_service');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
